### PR TITLE
Fixup eslint errors

### LINKED ISSUE #46: npm linting github action throwing error
The npm linter throws an error when it runs in the github action under:
https://github.com/codeforpdx/opentransit-metrics/blob/master/.github/workflows/test.yml
I disabled the workflow for now but it would be good to figure out the issue and fix it.

See this action as an example of the error:
https://github.com/codeforpdx/opentransit-metrics/runs/7928966223?check_suite_focus=true

It can be recreated locally:
```
docker run opentransit/react-dev:latest npm run lint:check

> opentransit-metrics@0.5.0 lint:check /app/frontend
> eslint src --ext .jsx,.js


/app/frontend/src/actions/index.js
  347:1   error    Delete `··`                               prettier/prettier
  348:1   error    Delete `··`                               prettier/prettier
  349:3   error    Delete `··`                               prettier/prettier
  351:1   error    Delete `··`                               prettier/prettier
  352:35  error    Insert `{`                                prettier/prettier
  353:7   error    Delete `{`                                prettier/prettier
  355:30  error    Insert `,`                                prettier/prettier
  356:1   error    Replace `······}·` with `····})`          prettier/prettier
  357:5   error    Delete `)`                                prettier/prettier
  360:7   error    Unexpected var, use let or const instead  no-var
  360:58  error    Insert `;`                                prettier/prettier
  361:7   error    Unexpected var, use let or const instead  no-var
  361:42  error    Insert `;`                                prettier/prettier
  362:19  error    Insert `;`                                prettier/prettier
  363:36  error    Insert `;`                                prettier/prettier
  364:16  error    Insert `;`                                prettier/prettier
  365:17  error    Insert `;`                                prettier/prettier
  366:61  error    Insert `;`                                prettier/prettier
  368:1   error    Replace `····⏎··};` with `}`              prettier/prettier
  375:5   warning  Unexpected console statement              no-console
  601:5   warning  Unexpected console statement              no-console

/app/frontend/src/components/RouteSummary.jsx
    8:1  error    `@material-ui/core/Button` import should occur before import of `./SummaryRow`  import/order
   50:1  error    Delete `⏎`                                                                      prettier/prettier
   55:5  warning  Unexpected console statement                                                    no-console
  217:7  error    Insert `··`                                                                     prettier/prettier
  218:7  error    Insert `··`                                                                     prettier/prettier
  219:1  error    Replace `······` with `········`                                                prettier/prettier
  220:1  error    Insert `··`                                                                     prettier/prettier
  222:1  error    Insert `··`                                                                     prettier/prettier

✖ 29 problems (26 errors, 3 warnings)
  26 errors and 0 warnings potentially fixable with the `--fix` option.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! opentransit-metrics@0.5.0 lint:check: `eslint src --ext .jsx,.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the opentransit-metrics@0.5.0 lint:check script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-08-26T03_50_00_624Z-debug.log
```

### PR DESCRIPTION
**Pull request by nkanderson**
Adds automated fixes from `eslint` and re-enables the check in CI. Fixes #46.

### CODE REVIEW

**Comment by nkanderson** [comment]
Opening this as a draft for testing, and because I think it might be good to add a git hook (maybe pre-push?) so contributors get some kind of feedback regarding running eslint prior to opening a PR.

**Comment by nkanderson** [comment]
@sidetrackedmind I ended up including a pre-commit hook that users can opt in to by configuring git locally to use the added `.githooks` directory for git hooks (I added the command for this to the docs). I'm not at all tied to this addition - I think it might be helpful, but probably the biggest thing is just getting folks to run the existing `dev/docker-lint.sh` script if they see the eslint step fail in CI on their PRs.

**Comment by sidetrackedmind** [comment]
Thanks for taking a look at this @nkanderson!

If I'm understanding your changes correctly, the linter was failing because there were actual linting problems in 2 of the frontend files? 

I like your idea of getting people to run the linter _before_ they make a PR. Is there any way to _force_ users to use the pre-commit hook? Build it into the docker or something? It's a little annoying but ultimately, it would be good if everyone caught the errors locally.

**Review by sidetrackedmind — APPROVED** [review]
I like this! Thanks for coming up with a solution to our linting problem.

**Comment by nkanderson** [comment]
> I think we can encourage people to update their git configuration locally to use the pre-commit hook and catch the linting errors ahead of time.

That sounds good to me! Maybe it could be a part of any front-end onboarding we do with new contributors.

> If people commit often and we start with a lint free repo, it shouldn't be too difficult to fix any lint errors that come up.

Agreed! And hopefully most errors that crop up can be automatically fixed by `eslint`, using the `--fix` option.

**Pull request merged**
