### PR TITLE
Show more detailed errors on headway calculation errors

### PR DESCRIPTION
**Pull request by liamphmurphy**
Here's what it looks like right now: 

image

Open to any suggestions as I'm not a front-end guy.

### CODE REVIEW

**Comment by youngj** [comment]
If there is no data for headway calculations, there may still be other data to display (such as scheduled statistics), so it would be better to return `None` from `get_headway_schedule_deltas` and not raise an exception. 

Since there must be at least two departure times in a day in order to compute headways, `get_headway_schedule_deltas` could skip any days that have less than two observed or scheduled departure times:

```
                if len(departure_time_values) < 2 or len(scheduled_departure_time_values) < 2:
                    continue
```

If there are no days with valid data, `get_headway_schedule_deltas` could return `None`:

```
        if len(headway_delta_arr) == 0:
            return None
```

**Comment by liamphmurphy** [comment]
Strangely when I return None when the len is 0, I get this error: `must have at least one array to concatenate`. I can't figure out what the execution flow leading to this is, but with the try / catch it is returning data. Could be something else odd going on.

When still using the try catch but then adding the len < 2 check, this error occurs again: `Error: error loading data for the requested calculation: direction_id: 1, start_stop_id: 5576, exact error: need at least one array to concatenate`

So the error is happening whether we return None or not; it seems to be something going on in the GraphQL library. 

If you have any thoughts I'm all ears, this behavior seems kind of odd

**Comment by youngj** [comment]
The docker-compose window should show a stack trace so you can see where `np.concat` is throwing the exception and avoid calling `np.concat` if he argument is empty. This seemed to work for me (in backend/models/metrics.py):

```
    def get_headway_schedule_deltas(self, direction_id, stop_id, rng: Range):

        headway_delta_arr = []

        now = time.time()

        for d in rng.dates:
            key = f'{direction_id}-{stop_id}-{d}-{rng.start_time_str}-{rng.end_time_str}-{rng.tz}'
            if key not in self.headway_schedule_deltas:
                timetable_df = self.get_timetable_data_frame(d, direction_id=direction_id, stop_id=stop_id)
                history_df = self.get_history_data_frame(d, direction_id=direction_id, stop_id=stop_id)

                departure_time_values = np.sort(history_df['DEPARTURE_TIME'].values)

                scheduled_departure_time_values = np.sort(timetable_df['DEPARTURE_TIME'].values)

                if len(departure_time_values) < 2 or len(scheduled_departure_time_values) < 2:
                    continue

                comparison_df = timetables.match_actual_times_to_schedule(
                    departure_time_values,
                    scheduled_departure_time_values
                )
                comparison_df['DEPARTURE_TIME'] = departure_time_values

                comparison_df['headway'] = np.r_[np.nan, compute_headway_minutes(departure_time_values)]

                comparison_df = comparison_df[np.isfinite(comparison_df['headway'].values) & np.isfinite(comparison_df['closest_scheduled_headway'].values)]

                if len(comparison_df) and comparison_df['DEPARTURE_TIME'].iloc[-1] >= now:
                    comparison_df = comparison_df[comparison_df['DEPARTURE_TIME'] < now]

                start_time = util.get_timestamp_or_none(d, rng.start_time_str, rng.tz)
                end_time = util.get_timestamp_or_none(d, rng.end_time_str, rng.tz)

                if start_time is not None:
                    comparison_df = comparison_df[comparison_df['DEPARTURE_TIME'] >= start_time]

                if end_time is not None:
                    comparison_df = comparison_df[comparison_df['DEPARTURE_TIME'] < end_time]

                self.headway_schedule_deltas[key] = comparison_df['headway'].values - comparison_df['closest_scheduled_headway'].values

            headway_delta_arr.append(self.headway_schedule_deltas[key])

        if len(headway_delta_arr) == 0:
            return None
        if len(headway_delta_arr) == 1:
            return headway_delta_arr[0]
        else:
            return np.concatenate(headway_delta_arr)
```

**Comment by youngj** [comment]
Removing the try/except block in TripIntervalMetrics would be necessary to see the original stack trace. It's better not to catch all Exception objects since it can make it harder to resolve logic errors in the code like this.

**Comment by liamphmurphy** [comment]
I think I'm experiencing some weird behavior with the flask hot-reloading feature, should probably just stick to restarting docker-compose. Just pushed up what's working and it's pretty much what you have.

**Comment by youngj** [comment]
Looks like this fixes the bug. Since the backend shouldn't normally throw exceptions if statistics aren't calculated for the requested date, showing "this may be because our systems have not yet calculated the statistics for your requested date range" for any GraphQL error doesn't seem necessary anymore.

**Review by youngj — APPROVED** [review]

**Pull request merged**
