### PR TITLE
add download button using already existing geojson data

### PR DESCRIPTION
**Pull request by liamphmurphy**
This would implement #11.

The calculations for the Isochrone page already exposed the data in a GeoJSON format; this PR adds a button so the user can download that data for the current route calculation shown.

Clicking the button will download a file of the name "geojson-export-'todays-date'.json".

Below is an example of the page with the new button, on the bottom-left: 
image

### CODE REVIEW

**Comment by sidetrackedmind** [comment]
Hey Liam - this is a good start!

I just tested out the feature. 

I think the download button is downloading the _latest_ geojson shape, not all the geojson shapes. For example, here's a snippet of what I see on the isochrone page and what I see in QGIS.

Isochrone page
image

QGIS
image

It would be good to get all the geojson shapes into the same .geojson file and add attributes to identify which is which. I think you will get 1 shape per color:
image

So it would be good to add an attribute to each shape like:
```
{trip_time: 5, color: blue, geometry: MultiPolygon (), ... }
```

I'm happy to chat through the above with you. Let me know :).

**Comment by liamphmurphy** [comment]
Good callout, I should get a GIS viewer and use that for testing.

I think it's only getting the latest due to some React stuff I have a vague idea of but don't fully understand. Will mess around and see how I can maintain the entire list of geoJSON though as each shape is calculated.

**Comment by sidetrackedmind** [comment]
Very minor but if you select no routes and/or you click on an area that produces no isochrone - it throws this error

**Comment by sidetrackedmind** [comment]
Nice! The geojson is getting cleared now 🙌 . YAY!

**Review by sidetrackedmind — APPROVED** [review]
Looks like it's working well. I'm going to approve it. Thanks for all the hard work on this @liamphmurphy 💯 .

**Pull request merged**
